### ISSUE TITLE
an TypeError

### ISSUE THREAD

**Issue by shen51000** [openai/DALL-E#45]
pytorch:1.7.1   torchversion: 0.8.2
when run the code,  it seems wrong:

Traceback (most recent call last):
  File "E:/github/DALL-E-master/test.py", line 46, in <module>
    display(T.ToPILImage(mode='RGB')(x[0]))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py", line 185, in __call__
    return F.to_pil_image(pic, self.mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchvision\transforms\functional.py", line 202, in to_pil_image
    'not {}'.format(type(npimg)))
TypeError: Input pic must be a torch.Tensor or NumPy ndarray, not <class 'numpy.ndarray'>
Original image:

**Comment by shen51000** [comment]
anyone who knows?

**Comment by shen51000** [comment]
lib version  cause
